apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: weather-monitor
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "1"
        autoscaling.knative.dev/maxScale: "1"
    spec:
      containers:
      - image: gcr.io/PROJECT_ID/weather-monitor:latest
        env:
        - name: TZ
          value: "Asia/Seoul"
        resources:
          limits:
            cpu: "500m"
            memory: "512Mi"
          requests:
            cpu: "100m"
            memory: "128Mi" 